package com.yungert.treinplanner.presentation.ui.model

import androidx.annotation.Keep

@Keep
data class StationNamen(
    val displayValue: String,
    val hiddenValue: String,
    var favorite: Boolean = false,
    var distance: Double = -1.0,
    var afstandTotGebruiker: String = ""
)

@Keep
var stationNamen = listOf(
    StationNamen("'s-Hertogenbosch", "ht"),
    StationNamen("'s-Hertogenbosch Oost", "hto"),
    StationNamen("'t Harde", "hde"),
    StationNamen("Aalten", "atn"),
    StationNamen("Abcoude", "ac"),
    StationNamen("Akkrum", "akm"),
    StationNamen("Alkmaar", "amr"),
    StationNamen("Alkmaar Noord", "amrn"),
    StationNamen("Almelo", "aml"),
    StationNamen("Almelo de Riet", "amri"),
    StationNamen("Almere Buiten", "almb"),
    StationNamen("Almere Centrum", "alm"),
    StationNamen("Almere Muziekwijk", "almm"),
    StationNamen("Almere Oostvaarders", "almo"),
    StationNamen("Almere Parkwijk", "almp"),
    StationNamen("Almere Poort", "ampo"),
    StationNamen("Alphen a/d Rijn", "apn"),
    StationNamen("Amersfoort Centraal", "amf"),
    StationNamen("Amersfoort Schothorst", "amfs"),
    StationNamen("Amersfoort Vathorst", "avat"),
    StationNamen("Amsterdam Amstel", "asa"),
    StationNamen("Amsterdam Bijlmer ArenA", "asb"),
    StationNamen("Amsterdam Centraal", "asd"),
    StationNamen("Amsterdam Holendrecht", "ashd"),
    StationNamen("Amsterdam Lelylaan", "asdl"),
    StationNamen("Amsterdam Muiderpoort", "asdm"),
    StationNamen("Amsterdam RAI", "rai"),
    StationNamen("Amsterdam Science Park", "assp"),
    StationNamen("Amsterdam Sloterdijk", "ass"),
    StationNamen("Amsterdam Zuid", "asdz"),
    StationNamen("Anna Paulowna", "ana"),
    StationNamen("Apeldoorn", "apd"),
    StationNamen("Apeldoorn De Maten", "apdm"),
    StationNamen("Apeldoorn Osseveld", "apdo"),
    StationNamen("Appingedam", "apg"),
    StationNamen("Arkel", "akl"),
    StationNamen("Arnemuiden", "arn"),
    StationNamen("Arnhem Centraal", "ah"),
    StationNamen("Arnhem Presikhaaf", "ahpr"),
    StationNamen("Arnhem Velperpoort", "ahp"),
    StationNamen("Arnhem Zuid", "ahz"),
    StationNamen("Assen", "asn"),
    StationNamen("Baarn", "brn"),
    StationNamen("Bad Nieuweschans", "nsch"),
    StationNamen("Baflo", "bf"),
    StationNamen("Barendrecht", "brd"),
    StationNamen("Barneveld Centrum", "bnc"),
    StationNamen("Barneveld Noord", "bnn"),
    StationNamen("Barneveld Zuid", "bnz"),
    StationNamen("Bedum", "bdm"),
    StationNamen("Beek-Elsloo", "bk"),
    StationNamen("Beesd", "bsd"),
    StationNamen("Beilen", "bl"),
    StationNamen("Bergen op Zoom", "bgn"),
    StationNamen("Best", "bet"),
    StationNamen("Beverwijk", "bv"),
    StationNamen("Bilthoven", "bhv"),
    StationNamen("Blerick", "br"),
    StationNamen("Bloemendaal", "bll"),
    StationNamen("Bodegraven", "bdg"),
    StationNamen("Borne", "bn"),
    StationNamen("Boskoop", "bsk"),
    StationNamen("Boskoop Snijdelwijk", "bsks"),
    StationNamen("Boven-Hardinxveld", "bhdv"),
    StationNamen("Bovenkarspel Flora", "bkf"),
    StationNamen("Bovenkarspel-Grootebroek", "bkg"),
    StationNamen("Boxmeer", "bmr"),
    StationNamen("Boxtel", "btl"),
    StationNamen("Breda", "bd"),
    StationNamen("Breda-Prinsenbeek", "bdpb"),
    StationNamen("Breukelen", "bkl"),
    StationNamen("Brummen", "bmn"),
    StationNamen("Buitenpost", "bp"),
    StationNamen("Bunde", "bde"),
    StationNamen("Bunnik", "bnk"),
    StationNamen("Bussum Zuid", "bsmz"),
    StationNamen("Capelle Schollevaar", "cps"),
    StationNamen("Castricum", "cas"),
    StationNamen("Chevremont", "cvm"),
    StationNamen("Coevorden", "co"),
    StationNamen("Cuijk", "ck"),
    StationNamen("Culemborg", "cl"),
    StationNamen("Daarlerveen", "da"),
    StationNamen("Dalen", "dln"),
    StationNamen("Dalfsen", "dl"),
    StationNamen("De Vink", "dvnk"),
    StationNamen("De Westereen", "dwe"),
    StationNamen("Deinum", "dei"),
    StationNamen("Delden", "ddn"),
    StationNamen("Delft", "dt"),
    StationNamen("Delft Campus", "dtcp"),
    StationNamen("Delfzijl", "dz"),
    StationNamen("Delfzijl West", "dzw"),
    StationNamen("Den Dolder", "dld"),
    StationNamen("Den Haag Centraal", "gvc"),
    StationNamen("Den Haag HS", "gv"),
    StationNamen("Den Haag Laan v NOI", "laa"),
    StationNamen("Den Haag Mariahoeve", "gvm"),
    StationNamen("Den Haag Moerwijk", "gvmw"),
    StationNamen("Den Haag Ypenburg", "ypb"),
    StationNamen("Den Helder", "hdr"),
    StationNamen("Den Helder Zuid", "hdrz"),
    StationNamen("Deurne", "dn"),
    StationNamen("Deventer", "dv"),
    StationNamen("Deventer Colmschate", "dvc"),
    StationNamen("Didam", "did"),
    StationNamen("Diemen", "dmn"),
    StationNamen("Diemen Zuid", "dmnz"),
    StationNamen("Dieren", "dr"),
    StationNamen("Doetinchem", "dtc"),
    StationNamen("Doetinchem De Huet", "dtch"),
    StationNamen("Dordrecht", "ddr"),
    StationNamen("Dordrecht Stadspolders", "ddrs"),
    StationNamen("Dordrecht Zuid", "ddzd"),
    StationNamen("Driebergen-Zeist", "db"),
    StationNamen("Driehuis", "drh"),
    StationNamen("Dronryp", "drp"),
    StationNamen("Dronten", "dron"),
    StationNamen("Duiven", "dvn"),
    StationNamen("Duivendrecht", "dvd"),
    StationNamen("Echt", "ec"),
    StationNamen("Ede Centrum", "edc"),
    StationNamen("Ede-Wageningen", "ed"),
    StationNamen("Eemshaven", "eem"),
    StationNamen("Eijsden", "edn"),
    StationNamen("Eindhoven Centraal", "ehv"),
    StationNamen("Eindhoven Strijp-S", "ehs"),
    StationNamen("Elst", "est"),
    StationNamen("Emmen", "emn"),
    StationNamen("Emmen Zuid", "emnz"),
    StationNamen("Enkhuizen", "ekz"),
    StationNamen("Enschede", "es"),
    StationNamen("Enschede De Eschmarke", "ese"),
    StationNamen("Enschede Kennispark", "esk"),
    StationNamen("Ermelo", "eml"),
    StationNamen("Etten-Leur", "etn"),
    StationNamen("Eygelshoven", "egh"),
    StationNamen("Eygelshoven Markt", "eghm"),
    StationNamen("FeanwÃ¢lden", "fwd"),
    StationNamen("Franeker", "fn"),
    StationNamen("Gaanderen", "gdr"),
    StationNamen("Geldermalsen", "gdm"),
    StationNamen("Geldrop", "gp"),
    StationNamen("Geleen Oost", "gln"),
    StationNamen("Geleen-Lutterade", "lut"),
    StationNamen("Gilze-Rijen", "gz"),
    StationNamen("Glanerbrug", "gbr"),
    StationNamen("Goes", "gs"),
    StationNamen("Goor", "go"),
    StationNamen("Gorinchem", "gr"),
    StationNamen("Gouda", "gd"),
    StationNamen("Gouda Goverwelle", "gdg"),
    StationNamen("Gramsbergen", "gbg"),
    StationNamen("Grijpskerk", "gk"),
    StationNamen("Groningen", "gn"),
    StationNamen("Groningen Europapark", "gerp"),
    StationNamen("Groningen Noord", "gnn"),
    StationNamen("Grou-Jirnsum", "gw"),
    StationNamen("Haarlem", "hlm"),
    StationNamen("Haarlem Spaarnwoude", "hlms"),
    StationNamen("Halfweg-Zwanenburg", "hwzb"),
    StationNamen("Hardenberg", "hdb"),
    StationNamen("Harderwijk", "hd"),
    StationNamen("Hardinxveld Blauwe Zoom", "hbzm"),
    StationNamen("Hardinxveld-Giessendam", "gnd"),
    StationNamen("Haren", "hrn"),
    StationNamen("Harlingen", "hlg"),
    StationNamen("Harlingen Haven", "hlgh"),
    StationNamen("Heemskerk", "hk"),
    StationNamen("Heemstede-Aerdenhout", "had"),
    StationNamen("Heerenveen", "hr"),
    StationNamen("Heerenveen IJsstadion", "hry"),
    StationNamen("Heerhugowaard", "hwd"),
    StationNamen("Heerlen", "hrl"),
    StationNamen("Heerlen Woonboulevard", "hrlw"),
    StationNamen("Heeze", "hze"),
    StationNamen("Heiloo", "hlo"),
    StationNamen("Heino", "hno"),
    StationNamen("Helmond", "hm"),
    StationNamen("Helmond 't Hout", "hmh"),
    StationNamen("Helmond Brandevoort", "hmbv"),
    StationNamen("Helmond Brouwhuis", "hmbh"),
    StationNamen("Hemmen-Dodewaard", "hmn"),
    StationNamen("Hengelo", "hgl"),
    StationNamen("Hengelo Gezondheidspark", "hglg"),
    StationNamen("Hengelo Oost", "hglo"),
    StationNamen("Hillegom", "hil"),
    StationNamen("Hilversum", "hvs"),
    StationNamen("Hilversum Media Park", "hvsm"),
    StationNamen("Hilversum Sportpark", "hvsp"),
    StationNamen("Hindeloopen", "hnp"),
    StationNamen("Hoensbroek", "hb"),
    StationNamen("Hoevelaken", "hvl"),
    StationNamen("Hollandsche Rading", "hor"),
    StationNamen("Holten", "hon"),
    StationNamen("Hoofddorp", "hfd"),
    StationNamen("Hoogeveen", "hgv"),
    StationNamen("Hoogezand-Sappemeer", "hgz"),
    StationNamen("Hoogkarspel", "hks"),
    StationNamen("Hoorn", "hn"),
    StationNamen("Hoorn Kersenboogerd", "hnk"),
    StationNamen("Horst-Sevenum", "hrt"),
    StationNamen("Houten", "htn"),
    StationNamen("Houten Castellum", "htnc"),
    StationNamen("Houthem-St. Gerlach", "sgl"),
    StationNamen("Hurdegaryp", "hdg"),
    StationNamen("IJlst", "ijt"),
    StationNamen("Kampen", "kpn"),
    StationNamen("Kampen Zuid", "kpnz"),
    StationNamen("Kapelle-Biezelinge", "bzl"),
    StationNamen("Kerkrade Centrum", "krd"),
    StationNamen("Kesteren", "ktr"),
    StationNamen("Klarenbeek", "kbk"),
    StationNamen("Klimmen-Ransdaal", "kmr"),
    StationNamen("Koog aan de Zaan", "kz"),
    StationNamen("Koudum-Molkwerum", "kmw"),
    StationNamen("Krabbendijke", "kbd"),
    StationNamen("Krommenie-Assendelft", "kma"),
    StationNamen("Kropswolde", "kw"),
    StationNamen("Kruiningen-Yerseke", "krg"),
    StationNamen("Lage Zwaluwe", "zlw"),
    StationNamen("Landgraaf", "lg"),
    StationNamen("Lansingerland-Zoetermeer", "llzm"),
    StationNamen("Leerdam", "ldm"),
    StationNamen("Leeuwarden", "lw"),
    StationNamen("Leeuwarden Camminghaburen", "lwc"),
    StationNamen("Leiden Centraal", "ledn"),
    StationNamen("Leiden Lammenschans", "ldl"),
    StationNamen("Lelystad Centrum", "lls"),
    StationNamen("Lichtenvoorde-Groenlo", "ltv"),
    StationNamen("Lochem", "lc"),
    StationNamen("Loppersum", "lp"),
    StationNamen("Lunteren", "ltn"),
    StationNamen("Maarheeze", "mz"),
    StationNamen("Maarn", "mrn"),
    StationNamen("Maarssen", "mas"),
    StationNamen("Maastricht", "mt"),
    StationNamen("Maastricht Noord", "mtn"),
    StationNamen("Maastricht Randwyck", "mtr"),
    StationNamen("Mantgum", "mg"),
    StationNamen("MariÃ«nberg", "mrb"),
    StationNamen("Martenshoek", "mth"),
    StationNamen("Meerssen", "mes"),
    StationNamen("Meppel", "mp"),
    StationNamen("Middelburg", "mdb"),
    StationNamen("Mook-Molenhoek", "mmlh"),
    StationNamen("Naarden-Bussum", "ndb"),
    StationNamen("Nieuw Amsterdam", "na"),
    StationNamen("Nieuw Vennep", "nvp"),
    StationNamen("Nieuwerkerk a/d IJssel", "nwk"),
    StationNamen("Nijkerk", "nkk"),
    StationNamen("Nijmegen", "nm"),
    StationNamen("Nijmegen Dukenburg", "nmd"),
    StationNamen("Nijmegen Goffert", "nmgo"),
    StationNamen("Nijmegen Heyendaal", "nmh"),
    StationNamen("Nijmegen Lent", "nml"),
    StationNamen("Nijverdal", "nvd"),
    StationNamen("Nunspeet", "ns"),
    StationNamen("Nuth", "nh"),
    StationNamen("Obdam", "obd"),
    StationNamen("Oisterwijk", "ot"),
    StationNamen("Oldenzaal", "odz"),
    StationNamen("Olst", "ost"),
    StationNamen("Ommen", "omn"),
    StationNamen("Oosterbeek", "otb"),
    StationNamen("Opheusden", "op"),
    StationNamen("Oss", "o"),
    StationNamen("Oss West", "ow"),
    StationNamen("Oudenbosch", "odb"),
    StationNamen("Overveen", "ovn"),
    StationNamen("Purmerend", "pmr"),
    StationNamen("Purmerend Overwhere", "pmo"),
    StationNamen("Purmerend Weidevenne", "pmw"),
    StationNamen("Putten", "pt"),
    StationNamen("Raalte", "rat"),
    StationNamen("Ravenstein", "rvs"),
    StationNamen("Reuver", "rv"),
    StationNamen("Rheden", "rh"),
    StationNamen("Rhenen", "rhn"),
    StationNamen("Rijssen", "rsn"),
    StationNamen("Rijswijk", "rsw"),
    StationNamen("Rilland-Bath", "rb"),
    StationNamen("Roermond", "rm"),
    StationNamen("Roodeschool", "rd"),
    StationNamen("Roosendaal", "rsd"),
    StationNamen("Rosmalen", "rs"),
    StationNamen("Rotterdam Alexander", "rta"),
    StationNamen("Rotterdam Blaak", "rtb"),
    StationNamen("Rotterdam Centraal", "rtd"),
    StationNamen("Rotterdam Lombardijen", "rlb"),
    StationNamen("Rotterdam Noord", "rtn"),
    StationNamen("Rotterdam Stadion", "rtst"),
    StationNamen("Rotterdam Zuid", "rtz"),
    StationNamen("Ruurlo", "rl"),
    StationNamen("Santpoort Noord", "sptn"),
    StationNamen("Santpoort Zuid", "sptz"),
    StationNamen("Sassenheim", "ssh"),
    StationNamen("Sauwerd", "swd"),
    StationNamen("Schagen", "sgn"),
    StationNamen("Scheemda", "sda"),
    StationNamen("Schiedam Centrum", "sdm"),
    StationNamen("Schin op Geul", "sog"),
    StationNamen("Schinnen", "sn"),
    StationNamen("Schiphol Airport", "shl"),
    StationNamen("Sittard", "std"),
    StationNamen("Sliedrecht", "sdt"),
    StationNamen("Sliedrecht Baanhoek", "sdtb"),
    StationNamen("Sneek", "sk"),
    StationNamen("Sneek Noord", "sknd"),
    StationNamen("Soest", "st"),
    StationNamen("Soest Zuid", "stz"),
    StationNamen("Soestdijk", "sd"),
    StationNamen("Spaubeek", "sbk"),
    StationNamen("Stavoren", "stv"),
    StationNamen("Stedum", "stm"),
    StationNamen("Steenwijk", "swk"),
    StationNamen("Susteren", "srn"),
    StationNamen("Swalmen", "sm"),
    StationNamen("Tegelen", "tg"),
    StationNamen("Terborg", "tbg"),
    StationNamen("Tiel", "tl"),
    StationNamen("Tiel Passewaaij", "tpsw"),
    StationNamen("Tilburg", "tb"),
    StationNamen("Tilburg Reeshof", "tbr"),
    StationNamen("Tilburg Universiteit", "tbu"),
    StationNamen("Twello", "twl"),
    StationNamen("Uitgeest", "utg"),
    StationNamen("Uithuizen", "uhz"),
    StationNamen("Uithuizermeeden", "uhm"),
    StationNamen("Usquert", "ust"),
    StationNamen("Utrecht Centraal", "ut"),
    StationNamen("Utrecht Leidsche Rijn", "utlr"),
    StationNamen("Utrecht Lunetten", "utln"),
    StationNamen("Utrecht Maliebaan", "utm"),
    StationNamen("Utrecht Overvecht", "uto"),
    StationNamen("Utrecht Terwijde", "utt"),
    StationNamen("Utrecht Vaartsche Rijn", "utvr"),
    StationNamen("Utrecht Zuilen", "utzl"),
    StationNamen("Valkenburg", "vk"),
    StationNamen("Varsseveld", "vsv"),
    StationNamen("Veendam", "vdm"),
    StationNamen("Veenendaal Centrum", "vndc"),
    StationNamen("Veenendaal West", "vndw"),
    StationNamen("Veenendaal-De Klomp", "klp"),
    StationNamen("Velp", "vp"),
    StationNamen("Venlo", "vl"),
    StationNamen("Venray", "vry"),
    StationNamen("Vierlingsbeek", "vlb"),
    StationNamen("Vleuten", "vtn"),
    StationNamen("Vlissingen", "vs"),
    StationNamen("Vlissingen Souburg", "vss"),
    StationNamen("Voerendaal", "vdl"),
    StationNamen("Voorburg", "vb"),
    StationNamen("Voorhout", "vh"),
    StationNamen("Voorschoten", "vst"),
    StationNamen("Voorst-Empe", "vem"),
    StationNamen("Vorden", "vd"),
    StationNamen("Vriezenveen", "vz"),
    StationNamen("Vroomshoop", "vhp"),
    StationNamen("Vught", "vg"),
    StationNamen("Waddinxveen", "wad"),
    StationNamen("Waddinxveen Noord", "wadn"),
    StationNamen("Waddinxveen Triangel", "wadt"),
    StationNamen("Warffum", "wfm"),
    StationNamen("Weert", "wt"),
    StationNamen("Weesp", "wp"),
    StationNamen("Wehl", "wl"),
    StationNamen("Westervoort", "wtv"),
    StationNamen("Wezep", "wz"),
    StationNamen("Wierden", "wdn"),
    StationNamen("Wijchen", "wc"),
    StationNamen("Wijhe", "wh"),
    StationNamen("Winschoten", "ws"),
    StationNamen("Winsum", "wsm"),
    StationNamen("Winterswijk", "ww"),
    StationNamen("Winterswijk West", "www"),
    StationNamen("Woerden", "wd"),
    StationNamen("Wolfheze", "wf"),
    StationNamen("Wolvega", "wv"),
    StationNamen("Workum", "wk"),
    StationNamen("Wormerveer", "wm"),
    StationNamen("Zaandam", "zd"),
    StationNamen("Zaandam Kogerveld", "zdk"),
    StationNamen("Zaandijk Zaanse Schans", "zzs"),
    StationNamen("Zaltbommel", "zbm"),
    StationNamen("Zandvoort aan Zee", "zvt"),
    StationNamen("Zetten-Andelst", "za"),
    StationNamen("Zevenaar", "zv"),
    StationNamen("Zevenbergen", "zvb"),
    StationNamen("Zoetermeer", "ztm"),
    StationNamen("Zoetermeer Oost", "ztmo"),
    StationNamen("Zuidbroek", "zb"),
    StationNamen("Zuidhorn", "zh"),
    StationNamen("Zutphen", "zp"),
    StationNamen("Zwijndrecht", "zwd"),
    StationNamen("Zwolle", "zl"),
    StationNamen("Zwolle Stadshagen", "zlsh")
)
